# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0004_charclass_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=512)),
                ('bonus', models.IntegerField(null=True)),
                ('item_type', models.CharField(max_length=512, blank=True)),
                ('check_penalty', models.IntegerField(null=True, blank=True)),
                ('spell_failure', models.IntegerField(null=True, blank=True)),
                ('weight', models.IntegerField(null=True, blank=True)),
                ('properties', models.CharField(max_length=512, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=512)),
                ('is_public', models.BooleanField(default=False)),
                ('alignment', models.CharField(default=b'N', max_length=512, choices=[(b'LG', b'LG'), (b'LN', b'LN'), (b'LE', b'LE'), (b'NG', b'NG'), (b'N', b'N'), (b'NE', b'NE'), (b'CG', b'CG'), (b'CN', b'CN'), (b'CE', b'CE')])),
                ('char_class', models.CharField(max_length=512, blank=True)),
                ('level', models.PositiveIntegerField(default=1, null=True)),
                ('deity', models.CharField(max_length=512, blank=True)),
                ('homeland', models.CharField(max_length=512, blank=True)),
                ('race', models.CharField(max_length=512, blank=True)),
                ('gender', models.CharField(default=b'M', max_length=512, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')])),
                ('size', models.CharField(default=b'0', max_length=512, choices=[(b'-8', b'Colossal'), (b'-4', b'Gargantuan'), (b'-2', b'Huge'), (b'-1', b'Large'), (b'0', b'Medium'), (b'1', b'Small'), (b'2', b'Tiny'), (b'4', b'Diminutive'), (b'8', b'Fine')])),
                ('age', models.PositiveIntegerField(null=True, blank=True)),
                ('height', models.CharField(max_length=512, blank=True)),
                ('weight', models.CharField(max_length=512, blank=True)),
                ('hair', models.CharField(max_length=512, blank=True)),
                ('eyes', models.CharField(max_length=512, blank=True)),
                ('hp_total', models.PositiveIntegerField(null=True)),
                ('current_hp', models.IntegerField(null=True, blank=True)),
                ('languages', models.TextField(blank=True)),
                ('xp', models.CommaSeparatedIntegerField(default=b'0,0', max_length=512)),
                ('speed', models.CommaSeparatedIntegerField(default=b'30,0,0,0,0,0', max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sheet_type', models.CharField(default=b'pathfinder', max_length=512)),
                ('slug', models.SlugField(unique=True, editable=False)),
                ('guid', models.CharField(unique=True, max_length=512, editable=False)),
                ('str_score', models.CommaSeparatedIntegerField(default=b'10,0', max_length=512)),
                ('dex_score', models.CommaSeparatedIntegerField(default=b'10,0', max_length=512)),
                ('con_score', models.CommaSeparatedIntegerField(default=b'10,0', max_length=512)),
                ('int_score', models.CommaSeparatedIntegerField(default=b'10,0', max_length=512)),
                ('wis_score', models.CommaSeparatedIntegerField(default=b'10,0', max_length=512)),
                ('cha_score', models.CommaSeparatedIntegerField(default=b'10,0', max_length=512)),
                ('base_attack', models.PositiveIntegerField(default=b'0', blank=True)),
                ('init_mod', models.IntegerField(null=True, blank=True)),
                ('ac_mods', models.CommaSeparatedIntegerField(default=b'0,0,0,0,0', max_length=512)),
                ('fort_save', models.CommaSeparatedIntegerField(default=b'0,0,0,0', max_length=512)),
                ('reflex_save', models.CommaSeparatedIntegerField(default=b'0,0,0,0', max_length=512)),
                ('will_save', models.CommaSeparatedIntegerField(default=b'0,0,0,0', max_length=512)),
                ('acro_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('appraise_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('bluff_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('climb_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('craft1_name', models.CharField(max_length=512, blank=True)),
                ('craft2_name', models.CharField(max_length=512, blank=True)),
                ('craft3_name', models.CharField(max_length=512, blank=True)),
                ('craft1_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('craft2_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('craft3_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('diplomacy_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('disable_dev_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('disguise_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('escape_art_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('fly_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('handle_animal_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('heal_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('intimidate_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('arcana_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('dungeon_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('engineering_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('geography_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('history_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('local_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('nature_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('nobility_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('planes_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('religion_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('linguistics_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('perception_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('perform1_name', models.CharField(max_length=512, blank=True)),
                ('perform2_name', models.CharField(max_length=512, blank=True)),
                ('perform1_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('perform2_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('prof1_name', models.CharField(max_length=512, blank=True)),
                ('prof2_name', models.CharField(max_length=512, blank=True)),
                ('prof1_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('prof2_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('ride_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('sense_motive_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('sleight_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('spellcraft_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('stealth_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('survival_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('swim_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('use_magic_skill', models.CommaSeparatedIntegerField(default=b'0,0,0', max_length=512)),
                ('damage_reduction', models.PositiveIntegerField(null=True, blank=True)),
                ('spell_resist', models.PositiveIntegerField(null=True, blank=True)),
                ('custom_feats', models.TextField(blank=True)),
                ('custom_spells', models.TextField(blank=True)),
                ('custom_special', models.TextField(blank=True)),
                ('loot', models.TextField(blank=True)),
                ('money', models.CommaSeparatedIntegerField(default=b'0,0,0,0', max_length=512)),
                ('feats', models.ManyToManyField(to='resources.Feat', blank=True)),
                ('player', models.ForeignKey(related_name='charactersheets', to=settings.AUTH_USER_MODEL)),
                ('special_abilities', models.ManyToManyField(to='resources.SpecialAbility', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SpellSchool',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=512)),
                ('spell_mod', models.CharField(default=b'int', max_length=512, choices=[(b'wis', b'Wisdom'), (b'int', b'Intelligence'), (b'cha', b'Charisma')])),
                ('known_spells', models.CommaSeparatedIntegerField(default=b'0,0,0,0,0,0,0,0,0', max_length=512)),
                ('spells_per_day', models.CommaSeparatedIntegerField(default=b'0,0,0,0,0,0,0,0,0', max_length=512)),
                ('bonus_spells', models.CommaSeparatedIntegerField(default=b'0,0,0,0,0,0,0,0', max_length=512)),
                ('character', models.ForeignKey(related_name='spell_schools', to='charactersheet.CharacterSheet')),
                ('spells', models.ManyToManyField(to='resources.Spell', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=512)),
                ('attack_bonus', models.CharField(max_length=512, blank=True)),
                ('crit_range', models.CharField(max_length=512, blank=True)),
                ('weapon_type', models.CharField(max_length=512, blank=True)),
                ('weapon_range', models.PositiveIntegerField(null=True, blank=True)),
                ('ammunition', models.PositiveIntegerField(null=True, blank=True)),
                ('damage', models.CharField(max_length=512, blank=True)),
                ('slug', models.SlugField(unique=True, editable=False)),
                ('guid', models.CharField(unique=True, max_length=512, editable=False)),
                ('character', models.ForeignKey(related_name='weapons', to='charactersheet.CharacterSheet')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='acitem',
            name='character',
            field=models.ForeignKey(related_name='items', to='charactersheet.CharacterSheet'),
            preserve_default=True,
        ),
    ]
